export const DUMMY_DATA = [
  {
    id: "project-alpha",
    title: "Project Alpha",
    description: "Develop a new AI-powered analytics platform.",
    startDate: "2024-01-15",
    endDate: "2025-07-25",
    status: "In Progress",
    progress: 65,
    team: [
      { name: "Alex J", color: "bg-blue-500" },
      { name: "Sam R", color: "bg-purple-500" },
      { name: "Taylor K", color: "bg-green-500" },
    ],
  },
  {
    id: "website-redesign",
    title: "Website Redesign",
    description: "Revamp the company's main website for better UX.",
    startDate: "2024-03-01",
    endDate: "2024-08-15",
    status: "Not Started",
    progress: 0,
    team: [
      { name: "Jamie L", color: "bg-yellow-500" },
      { name: "Casey M", color: "bg-pink-500" },
    ],
  },
  {
    id: "mobile-app",
    title: "Mobile App Development",
    description: "Create iOS and Android apps for customer engagement.",
    startDate: "2024-02-20",
    endDate: "2024-11-30",
    status: "In Progress",
    progress: 42,
    team: [
      { name: "Riley T", color: "bg-red-500" },
      { name: "Jordan P", color: "bg-indigo-500" },
      { name: "Morgan K", color: "bg-teal-500" },
    ],
  },
  {
    id: "database-migration",
    title: "Database Migration",
    description: "Migrate database to a new cloud-based solution.",
    startDate: "2024-04-10",
    endDate: "2024-07-20",
    status: "Completed",
    progress: 100,
    team: [
      { name: "Alex J", color: "bg-blue-500" },
      { name: "Casey M", color: "bg-pink-500" },
    ],
  },
  {
    id: "marketing-campaign",
    title: "Marketing Campaign Launch",
    description: "Plan and execute a new digital marketing campaign.",
    startDate: "2024-05-01",
    endDate: "2024-09-30",
    status: "In Progress",
    progress: 30,
    team: [
      { name: "Jamie L", color: "bg-yellow-500" },
      { name: "Taylor K", color: "bg-green-500" },
    ],
  },
  {
    id: "internal-tool",
    title: "Internal Tool Development",
    description: "Build a custom internal tool for project management.",
    startDate: "2024-06-01",
    endDate: "2024-12-31",
    status: "Not Started",
    progress: 0,
    team: [
      { name: "Riley T", color: "bg-red-500" },
      { name: "Morgan K", color: "bg-teal-500" },
    ],
  },
  {
    id: "cloud-infrastructure",
    title: "Cloud Infrastructure Setup",
    description: "Set up new cloud infrastructure for scalability.",
    startDate: "2024-01-01",
    endDate: "2024-03-31",
    status: "Completed",
    progress: 100,
    team: [
      { name: "Sam R", color: "bg-purple-500" },
      { name: "Jordan P", color: "bg-indigo-500" },
    ],
  },
  {
    id: "customer-portal",
    title: "Customer Portal",
    description: "Create a self-service portal for customers.",
    startDate: "2024-07-01",
    endDate: "2024-10-15",
    status: "In Progress",
    progress: 15,
    team: [
      { name: "Alex J", color: "bg-blue-500" },
      { name: "Taylor K", color: "bg-green-500" },
      { name: "Morgan K", color: "bg-teal-500" },
    ],
  },
];
